In [2]:
import tensorflow as tf

2025-01-15 09:06:27.391377: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-15 09:06:27.516030: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-15 09:06:27.608695: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1736931987.674081    5787 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1736931987.696862    5787 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-15 09:06:27.836736: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [3]:
x = tf.constant([[4]], shape=(1, 1),dtype = tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


2025-01-15 09:08:41.572134: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [4]:
x = tf.constant([[1,2,3],[4,5,6]],shape = (2,3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [6]:
x = tf.zeros((3, 2,5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [7]:
x = tf.ones(4,3)
print(x)

tf.Tensor([1 1 1 1], shape=(4,), dtype=int32)


In [8]:
x = tf.random.uniform((2,2),minval=0,maxval=1)
print(x)

tf.Tensor(
[[0.6995692  0.43190372]
 [0.21375477 0.5251044 ]], shape=(2, 2), dtype=float32)


In [9]:
x = tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 0.11649766  2.1414506   0.5951526 ]
 [-1.1621903   0.02856638  0.99196374]
 [-1.0040151   0.7736252   0.9605097 ]], shape=(3, 3), dtype=float32)


In [10]:
x = tf.range(9)
x = tf.range(start=0,limit=10,delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [11]:
# Math
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
z = x + y